### ISSUE TITLE
my search only returns fightclub and reacher

### ISSUE THREAD

**Issue by ArielAssaf** [dreulavelle/Prowlarr-Indexers#32]
no matter what I search for I get those results, which I think are the configured as tests.

Any suggestions would be appreciated.

**Comment by Bombole123** [comment]
As far as I know that's supposed to show up there according to the .yml file. Something to do with Radarr and Sonarr validation. However, I'm not getting any search results for Radarr and Sonarr after RSS sync. BUT, if I search in Prowlarr using imdb:tt123456 for example the movie comes up. I'm not sure what we're supposed to do to have Radarr or Sonarr pull up results from it.

**Comment by lexiismadd** [comment]
I'm experiencing the same

**Comment by shaboigan** [comment]
I have the same issue, when I manually run a rss sync I can see it passes a blank string to the Torrentio indexer and then it falls back to grabbing the validation titles e.g reacher and fight club

If I select automatic or interactive search on an individual episode I can see ID's and Episode numbers are passed to the Torrentio indexer

rsssync output
[Info] ReleaseSearchService: Searching indexer(s): [Torrentio] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000] 

automatic search on a single episode output
[Info] ReleaseSearchService: Searching indexer(s): [Torrentio] for Term: [] | ID(s): IMDbId:[11198330] for Season / Episode:[S02E01], Offset: 0, Limit: 100, Categories: [5000]

**Comment by shaboigan** [comment]
I'm still getting the same behaviour with the sonarr and radarr tags added to the tags section as you mentioned

If I select the manual search options from the show the query is passed to the indexer properly and a release is grabbed

<img width="1351" alt="Screenshot 2024-06-25 at 7 27 28 am" src="https://github.com/dreulavelle/Prowlarr-Indexers/assets/28205584/fd85d143-cb0c-468f-8d6f-b2cb4da93a75">

<img width="1238" alt="Screenshot 2024-06-25 at 7 31 56 am" src="https://github.com/dreulavelle/Prowlarr-Indexers/assets/28205584/4c2fc1d5-3bd9-42d3-a01d-91cc9657b9d0">


If I try to run a rss sync a blank query is passed to the indexer (instead of the test shows I have queued in the wanted/missing area) and nothing is grabbed or found
<img width="1576" alt="Screenshot 2024-06-25 at 7 35 20 am" src="https://github.com/dreulavelle/Prowlarr-Indexers/assets/28205584/59fd9854-ea7a-459f-8351-0000a7d0da5e">

<img width="1008" alt="Screenshot 2024-06-25 at 7 37 07 am" src="https://github.com/dreulavelle/Prowlarr-Indexers/assets/28205584/686bfcc0-77ca-4541-be9b-9ce91e438546">

When I run a rss sync on my non debrid sonarr I get releases grabbed without issue

**Comment by Bombole123** [comment]
I forgot I had to also modify the "Torrentio Options" to this:

providers=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetdl,horriblesubs,nyaasi|sort=qualitysize

I believe by default it was set to lookup 480p releases. I removed that and added more providers.

**Comment by dreulavelle** [comment]
Indexers have been updated.

**Comment by ArielAssaf** [comment]
> Indexers have been updated.

How did you fix it? I still have the same issue.

**Comment by dreulavelle** [comment]
fightclub and reacher are defaults when there are no torrents. make sure your searching properly. Be sure to read the readme in the repo

**Comment by Gtt1229** [comment]
I wanted to add to this after some testing.

It appears that for some reason or another, the Indexer in Sonarr requires both categories: TV and Movies to produce valid results.

In Prowlarr, changing `Settings -> Apps -> Sonarr -> Sync Categories -> + Movies`, and then resyncing the indexers worked. You can also just add the category from Sonarr if your indexer isn't Prowlarr managed.
